name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  test-jq:
    name: Run tests with jq
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -sOLJ 'https://github.com/jqlang/jq/releases/download/jq-1.8.0/jq-linux-amd64'
          chmod a+x jq-linux-amd64
          JQ=./jq-linux-amd64 make test-jq

  test-jqjq-jq:
    name: Run tests with jqjq using jq
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -sOLJ 'https://github.com/jqlang/jq/releases/download/jq-1.8.0/jq-linux-amd64'
          chmod a+x jq-linux-amd64
          JQ=./jq-linux-amd64 make test-jqjq

  test-jqjq-gojq:
    name: Run tests with jqjq using gojq
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -Ls 'https://github.com/itchyny/gojq/releases/download/v0.12.17/gojq_v0.12.17_linux_amd64.tar.gz' | tar xz
          mv gojq*/gojq gojq
          JQ=./gojq make test-jqjq

  test-jqjq-jaq:
    name: Run tests with jqjq using jaq
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -sOLJ 'https://github.com/01mf02/jaq/releases/download/v2.2.0/jaq-x86_64-unknown-linux-gnu'
          chmod a+x jaq-x86_64-unknown-linux-gnu
          JQ=./jaq-x86_64-unknown-linux-gnu make test-jqjq
